### ISSUE TITLE
Data action getSearchOrganizations not set up!

### ISSUE THREAD

**Issue by jazzankan** [coral-erm/coral#182]
I just installed 2.0.The path to ajax_htmldata.php was wrong in index.js. After correcting it I get "Data action getSearchOrganizations not set up!" An undefined class Organization() seems to be used. Where is that class? The other modules seems to be working.

**Comment by jeffnm** [comment]
Just so that I'm clear, did you install 2.0 from scratch or do an upgrade? 

Also, can you confirm that the index.js you are referring to is the one in `organizations/js/index.js`?

**Comment by jazzankan** [comment]
Istalled from scratch. It was "successfull" for all modules. But I might have made a mistake somewhere. If  I Ieave the organizations/js/index,js file untouched (and all other files), what i get is an eternal "Processing". No organizations are shown.  And the status is  500 for the ajax call to ajax_htmldata.php.  Changing the getSearchOrganizations action into some nonsens gives me "Action not set up!" But the status is now 200!

**Comment by jazzankan** [comment]
I downloaded all files again and replaced all files in organixations with fresh ones. Same result.
PHP Version 7.0.15-0ubuntu0.16.04.2

**Comment by jeffnm** [comment]
Thank you for that information. I'll investigate further and get back to you.

**Comment by jazzankan** [comment]
Thanks. This is what the error.log on the server says:
PHP Fatal Error: uncaught exception: There was a problem with the database : Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'coral_organizations.OHP.parentOrganizationID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/coral/$organi/organizations/admin/classes/common/DBService.php:39\nStack trace:\n#0 /var/www/coral/organizations/admin/classes/common/DBService.php(71): DBService->checkForError ()n#1 /var/www/html/coral/organizations/admin/classes/domain/Organization.php(550): DBService->processQuery('SELECT O-organi...', 'assoc')\n#2 /var/www/html/coral/organizations/ajax_htmldata.php(895): Organizations->search(Array, 'TRIM(LEADING 'T...', '')\n#3 {main}\n thrown in /var/www/hrml/coral/organizations/admin/classes/common/DBService.php on line 39, referer: http://89.45.232.133/coral/organizations

**Comment by jazzankan** [comment]
Also PHP Warning for line 545 in Organization.php.
while ($row = mysqli_fetch_assoc($result)){
Expects parameter 1 to be mysqli_result, boolean given

**Comment by jeffnm** [comment]
That's really strange. All of those files seem to be working fine in the 2.0 beta download I am testing with. Can you download a [fresh copy](https://github.com/Coral-erm/Coral/releases/tag/v2.0-beta) and replace your organizations directory with the organizations directory from the fresh download? Just be sure to keep your `organizations/admin/configuration.ini` file and it should be a seamless switch. 

@jsavell Do you have any thoughts about this? It doesn't seem like it's an install issue, unless the database wasn't created properly... but that doesn't explain the other issues.

@jazzankan can you verify that the organizations database was created properly?

**Comment by jsavell** [comment]
I would guess that it's a database version/configuration issue.

I just did a scratch installation from master and had no problems.

**Comment by jazzankan** [comment]
The problem starts with MySQL 5.7 . Did you use an earlier version of MySQL? I still think the code needs to be corrected!
A quick fix is to alter the SQL_mode, following this:
https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html
I tried, and now the search for organizations is successfull.

**Comment by rtatterson** [comment]
It appears this was resolved. Feel free to reopen if you are seeing the issue in the latest version.
