### ISSUE TITLE
PHP Fatal Error for Organizations on MySQL 5.7

### ISSUE THREAD

**Issue by t4k** [coral-erm/coral#235]
> PHP message: PHP Fatal error:  Uncaught Exception: There was a problem with the database: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'coral_organizations.OHP.parentOrganizationID’ which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/coral/organizations/admin/classes/common/DBService.php:39
> Stack trace:
> #0 /var/www/coral/organizations/admin/classes/common/DBService.php(71): DBService->checkForError()
> #1 /var/www/coral/organizations/admin/classes/domain/Organization.php(550): DBService->processQuery('SELECT O.organi…', 'assoc’)
> #2 /var/www/coral/organizations/ajax_htmldata.php(895): Organization->search(Array, ‘TRIM(LEADING ‘T…’, ‘’)
> #3 {main}
>   thrown in /var/www/coral/organizations/admin/classes/common/DBService.php on line 39

Diagnosed the problem and have an idea for a solution from: https://stackoverflow.com/a/34115425

Pull request coming shortly.

**Comment by t4k** [comment]
This issue is actually resolved.
