### ISSUE TITLE
Resource File Import failing

### ISSUE THREAD

**Issue by vinny75** [coral-erm/coral#481]
The File Import in the Resource module is failing with the following error:

[Mon Sep 10 09:08:47.778171 2018] [:error] [pid 1540] PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem with the database: Field 'resourceID' doesn't have a default value' in /var/www/html/coral3/resources/admin/classes/common/DBService.php:52
Stack trace:
#0 /var/www/html/coral3/resources/admin/classes/common/DBService.php(91): DBService->checkForError()
#1 /var/www/html/coral3/resources/admin/classes/common/DatabaseObject.php(245): DBService->processQuery('INSERT INTO `Re...')
#2 /var/www/html/coral3/resources/import.php(595): DatabaseObject->save()
#3 {main}
thrown in /var/www/html/coral3/resources/admin/classes/common/DBService.php on line 52, referer: /coral3/resources/import.php

I traced it back to line 575, "if (isset($proceed)) {"  which was added in merge #244
If I set $proceed to true before this line, the import works as expected.

**Comment by nkuitse** [comment]
Here's a patch that makes it so that all $foo->save() calls occur only when $proceed is true.
[resource-import-patch.txt](https://github.com/coral-erm/coral/files/2553913/resource-import-patch.txt)

**Comment by nkuitse** [comment]
Sorry, that was wrong; some $foo->save calls will occur whether $proceed is true or not: (1) New ResourceType, AcquisitionType, ResourceFormat, and GeneralSubject objects are saved; (2) Some parent resource stuff is saved -- I don't understand this code.

**Comment by veggiematts** [comment]
There is indeed a problem.
Test plan to reproduce the problem:

```
MariaDB [coral_resources_prod]> select max(resourceAcquisitionID) from ResourceAcquisition;
+----------------------------+
| max(resourceAcquisitionID) |
+----------------------------+
|                       6964 |
+----------------------------+
```
Start an import, until the preview page ("n resources will be imported" messages) but do not import.

```
MariaDB [coral_resources_prod]> select max(resourceAcquisitionID) from ResourceAcquisition;
+----------------------------+
| max(resourceAcquisitionID) |
+----------------------------+
|                       6966 |
+----------------------------+
```
