### ISSUE TITLE
Installer fails: Fatal error:  Uncaught UnexpectedValueException

### ISSUE THREAD

**Issue by mjlassila** [coral-erm/coral#587]
I'm getting a strange error when trying to update Coral from 2.0.0 to 3.0.1

The strange thing is, I'm able to run upgrade perfectly fine on my local test installation with PHP 7.2.1 but updating fails when trying to do it in a Docker container created from php:7.2-apache-stretch base image. I have patched Coral for PHP 7.2 compatibility using the script from https://github.com/coral-erm/coral/issues/360#issuecomment-437414786

> Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/html/install/installer.php on line 281

> Fatal error:  Uncaught UnexpectedValueException: The script for 'Licensing Module' has returned a null result (which is not allowed). in /var/www/html/install/installer.php:284
>Stack trace:
>#0 /var/www/html/install/installer.php(272): Installer->actuallyRunTest('licensing', NULL)
>#1 /var/www/html/install/installer.php(265): Installer->runTestForResult('licensing', Array)
>#2 /var/www/html/install/index.php(112): Installer->runTestForResult('upgrade_helper')
>#3 /var/www/html/install/index.php(196): run_loop('3.0.0')
>#4 /var/www/html/index.php(4): require_once('/var/www/html/i...')
>#5 {main}
 > thrown in /var/www/html/install/installer.php on line 284

The only difference between my local test installation and our production installation is that we are running DB in a separate host in production.

**Comment by mjlassila** [comment]
Same error arises when using made a test using current commit (528fa1719) from the development branch.
