### ISSUE TITLE
Resource module export failed with Note Type selected

### ISSUE THREAD

**Issue by xsong9** [coral-erm/coral#659]
The excel export function failed when the search results is filtered by Note Type. 
![coral export with note type](https://user-images.githubusercontent.com/10168937/88577632-58260a00-d015-11ea-890c-671f8c5e0257.png)

It generated http error 500. 
![Screen Shot 2020-07-27 at 2 28 01 PM](https://user-images.githubusercontent.com/10168937/88577681-6c6a0700-d015-11ea-83fc-4a08280c9895.png)

**Comment by veggiematts** [comment]
Indeed. Error in the log:
PHP Fatal error:  Uncaught Exception: There was a problem with the database: Unknown column 'RNA.noteTypeID' in 'where clause' in /home/coral/www/resources/admin/classes/common/DBService.php:52
Stack trace:
#0 /home/coral/www/resources/admin/classes/common/DBService.php(91): DBService->checkForError()
#1 /home/coral/www/resources/admin/classes/domain/Resource.php(1132): DBService->processQuery('SELECT R.resour...', 'assoc')
#2 /home/coral/www/resources/export.php(44): Resource->export(Array, 'R.createDate DE...')

**Comment by streatim** [comment]
Fixed in v2025.04.04.
