### ISSUE TITLE
Session expired makes resource creation fail

### ISSUE THREAD

**Issue by tuxayo** [coral-erm/coral#98]
- It shows a white page
- The url contains the login page HTML

```
http://localhost/coral/resources/resource.php?ref=new&resourceID=%3C!DOCTYPE%20html%20PUBLIC%20%22-//W3C//DTD%20XHTML%201.0%20Strict//EN%22%20%22http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd%22%3E%3Chtml%20xmlns=%22http://www.w3.org/1999/xhtml%22%20xml:lang=%22en%22%20lang=%22en%22%20dir=%22ltr%22%3E%3Chead%3E%3Cmeta%20http-equiv=%22Content-Type%22%20content=%22text/html;%20charset=utf-8%22%20/%3E%3Ctitle%3ECORAL%20Authentication%3C/title%3E%3Clink%20rel=%22stylesheet%22%20href=%22css/style.css%22%20type=%22text/css%22%20media=%22screen%22%20/%3E%3Clink%20rel=%22stylesheet%22%20href=%22css/thickbox.css%22%20type=%22text/css%22%20media=%22screen%22%20/%3E%3Clink%20rel=%22SHORTCUT%20ICON%22%20href=%22images/favicon.ico%22%20/%3E%3Clink%20rel=%22stylesheet%22%20href=%22//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css%22%3E%3Clink%20href=%27https://fonts.googleapis.com/css?family=Open+Sans:100,400,300,600,700%27%20rel=%27stylesheet%27%20type=%27text/css%27%3E%3Cscript%20type=%22text/javascript%22%20src=%22js/plugins/jquery.js%22%3E%3C/script%3E%3Cscript%20type=%22text/javascript%22%20src=%22js/plugins/thickbox.js%22%3E%3C/script%3E%3Cscript%20type=%22text/javascript%22%20src=%22js/common.js%22%3E%3C/script%3E%3Cscript%20type=%22text/javascript%22%20src=%22js/plugins/Gettext.js%22%3E%3C/script%3E%3C/head%3E%3Cbody%3E%3Cnoscript%3E%3Cfont%20face=%22arial%22%3EJavaScript%20must%20be%20enabled%20in%20order%20for%20you%20to%20use%20CORAL.%20However,%20it%20seems%20JavaScript%20is%20either%20disabled%20or%20not%20supported%20by%20your%20browser.%20To%20use%20CORAL,%20enable%20JavaScript%20by%20changing%20your%20browser%20options,%20then%20%3Ca%20href=%27%27%3Etry%20again%3C/a%3E.%3C/font%3E%3C/noscript%3E%3Ccenter%3E%3Cform%20name=%22loginForm%22%20method=%22post%22%20action=%22index.php?service=/coral/resources/ajax_processing.php?action=submitNewResource%22%3E%3Cbr%20/%3E%3Cdiv%20style=%22width:418px;%22%20id=%22login-form%22%3E%3Cdiv%20id=%22title-div%22%3E%20%20%20%20%20%20%20%20%3Cdiv%20id=%22img-title%22%3E%3Cimg%20src=%22images/authtitle.png%22%20/%3E%3C/div%3E%20%20%20%20%20%20%20%20%3Cdiv%20id=%22text-title%22%3EeRM%20Authentication%3C/div%3E%20%20%20%20%20%20%20%20%3Cdiv%20class=%22clear%22%3E%3C/div%3E%20%20%20%20%3C/div%3E%3Cdiv%20id=%22login-content%22%3E%3Clabel%20style=%27width:100%;font-weight:normal;%27%3E%3Cspan%20class=%27smallerText%27%3EPlease%20enter%20login%20credentials%20to%20sign%20in.%3C/span%3E%3Cspan%20class=%27smallDarkRedText%27%3E%3C/span%3E%3C/label%3E%3Cbr%20/%3E%3Clabel%20for=%27loginID%27%3ELogin%20ID:%3C/label%3E%3Cinput%20type=%27text%27%20id=%27loginID%27%20name=%27loginID%27%20value=%22coral%22%20/%3E%3Cbr%20/%3E%3Clabel%20for=%27password%27%3EPassword:%3C/label%3E%3Cinput%20type=%27password%27%20id=%27password%27%20name=%27password%27%20value=%27%27%20/%3E%3Cbr%20/%3E%3C!--%20%3Clabel%20for=%27remember%27%3E&nbsp;%3C/label%3E%20--%3E%3Cinput%20type=%27checkbox%27%20id=%27remember%27%20name=%27remember%27%20value=%27Y%27%20style=%27margin:1px%205px%200px%200px;%20padding:0px;%27%20checked%20/%3E%3Cspan%20class=%27smallText%27%3ERemember%20my%20login%20ID%3C/span%3E%3Cbr%20/%3E%3Cinput%20type=%22submit%22%20value=%22Login%22%20id=%22loginbutton%22%20class=%22loginButton%22%20style=%27margin-top:17px;%27%20/%3E%3C/div%3E%3C/div%3E%3Cdiv%20class=%27boxRight%27%3E%3Cp%20class=%22fontText%22%3EChange%20language:%3C/p%3E%3Cselect%20name=%22lang%22%20id=%22lang%22%20class=%22dropDownLang%22%3E%3Coption%20value=%27en_US%27%20selected=%27selected%27%3EEnglish%3C/option%3E%3Coption%20value=%27fr_FR%27%3EFran%C3%A7ais%3C/option%3E%3C/select%3E%3C/div%3E%3Cdiv%20class=%27smallerText%27%20style=%27text-align:center;%20margin-top:13px;%27%3E%3Ca%20href=%27admin.php%27%3EAdmin%20page%3C/a%3E%3C/div%3E%3C/form%3E%3Cbr%20/%3E%3Cbr%20/%3E%3C/center%3E%3Cbr%20/%3E%3Cbr%20/%3E%20%20%20%20%3Cscript%3E%20%20%20%20%20%20%20%20/*%20%20%20%20%20%20%20%20%20*%20Functions%20to%20change%20the%20language%20with%20the%20dropdown%20%20%20%20%20%20%20%20%20*/%20%20%20%20%20%20%20%20$(%22#lang%22).change(function()%20{%20%20%20%20%20%20%20%20%20%20%20%20setLanguage($(%22#lang%22).val());%20%20%20%20%20%20%20%20%20%20%20%20location.reload();%20%20%20%20%20%20%20%20});%20%20%20%20%20%20%20%20//%20Create%20a%20cookie%20with%20the%20code%20of%20language%20%20%20%20%20%20%20%20function%20setLanguage(lang)%20{var%20wl%20=%20window.location,%20now%20=%20new%20Date(),%20time%20=%20now.getTime();%20%20%20%20%20%20%20%20%20%20%20%20var%20cookievalid=2592000000;%20//%2030%20days%20(1000*60*60*24*30)%20%20%20%20%20%20%20%20%20%20%20%20time%20+=%20cookievalid;now.setTime(time);document.cookie%20=%27lang=%27+lang+%27;path=/%27+%27;domain=%27+wl.host+%27;expires=%27+now;%20%20%20%20}%20%20%20%20%3C/script%3E%3Cscript%20type=%22text/javascript%22%3E//give%20focus%20to%20login%20formdocument.getElementById(%27loginID%27).focus();%3C/script%3E%3Cscript%20type=%22text/javascript%22%20src=%22js/index.js%22%3E%3C/script%3E%3C/body%3E%3C/html%3E
```
- This HTML ended up in the SQL query

```
[Thu Aug 04 16:04:24.963738 2016] [:error] [pid 11122] [client ::1:51382] PHP Fatal error:
Uncaught Exception: There was a problem with the database:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near
'https://fonts.googleapis.com/css?family=Open Sans:100,400,300,600,700' rel='styl'
at line 1 in
/srv/http/coral/resources/admin/classes/common/DBService.php:39
Stack trace:
#0 /srv/http/coral/resources/admin/classes/common/DBService.php(73): DBService->checkForError()
#1 /srv/http/coral/resources/admin/classes/common/DatabaseObject.php(290): DBService->processQuery('SELECT * FROM `...', 'assoc')
#2 /srv/http/coral/resources/admin/classes/common/DatabaseObject.php(63): DatabaseObject->load()
#3 /srv/http/coral/resources/admin/classes/common/Object.php(27): DatabaseObject->init(Object(NamedArguments))
#4 /srv/http/coral/resources/resource.php(23): Object->__construct(Object(NamedArguments))
#5 {main}  thrown in /srv/http/coral/resources/admin/classes/common/DBService.php on line 39, 
referer: http://localhost/coral/resources/index.php
```

To reproduce, just logout from another page.

From the URL it seems that the new resource form takes the response from the server and adds it in the URL.

**Comment by tuxayo** [comment]
Of course the form content is lost.

**Comment by jsavell** [comment]
This is because the redirect after new resource creating is dependent on submitNewResource.php to echo the ID of the newly created resource: 
https://github.com/Coral-erm/Coral/blob/master/resources/ajax_processing/submitNewResource.php#L57

A quick fix would be to test that `resourceID` with `Number.isInteger(resourceID)` before attempting the redirect, here:
https://github.com/Coral-erm/Coral/blob/master/resources/js/forms/resourceNewForm.js#L288

It would also be a good idea to return the resourceID as a JSON object to be parsed, rather than HTML.

**Comment by jsavell** [comment]
This is part of a broader issue with AJAX content and expired sessions. 

If I remember correctly, when an AJAX request is populating a modal, and the session is expired, it (unintentionally) loads the login form into the modal, but it's non-functional. You can't actually re-login through that form and instead need to reload the page.

I think we need a universal solution for detecting that  an AJAX request failed due to an expired session and in that case, redirect to the login form or something similar.

**Comment by tuxayo** [comment]
> I think we need a universal solution for detecting that an AJAX request failed due to an expired session

Would checking for a 302 be enough?

> in that case, redirect to the login form or something similar.

Or just display a message to ask login in another windows and retry to validate the form? I don't know how important it is to not loose the form content.

**Comment by techsvcslib** [comment]
This issue of session expiration in the Resources module is a major one. I run into this a lot and it is a very bad thing, especially when you are working through editing/adding dozens of records. There needs to be a better way to handle it and it’s a bigger issue than just the AJAX request.

Steve

On Aug 5, 2016, at 4:23 AM, Victor <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we need a universal solution for detecting that an AJAX request failed due to an expired session

Would checking for a 302 be enough?

in that case, redirect to the login form or something similar.

Or just display a message to ask login in another windows and retry to validate the form? I don't know how important it is to not loose the form content.

**Comment by tuxayo** [comment]
> There needs to be a better way to handle it and it’s a bigger issue than just the AJAX request.

What are the other use cases where session expiration is annoying?

Would resetting the session expiration when there is activity help? So the session would expire only after 1 hour not touching Coral. Now it expires one hour after login in.

**Comment by techsvcslib** [comment]
It should not expire after an hour, period, unless there is no activity at all. There have been many occasions where I’ve spent several minutes filling out details in a particular record only to have the timeout kick in and I lose everything I’ve done. This is a major problem. There should be some way that we detect inactivity vs. activity.

Steve

On Aug 5, 2016, at 5:36 AM, Victor <notifications@github.com<mailto:notifications@github.com>> wrote:


There needs to be a better way to handle it and it’s a bigger issue than just the AJAX request.

What are the other use cases where session expiration is annoying?

Would resetting the session expiration when there is activity help? So the session would expire only after 1 hour not touching Coral. Now it expires one hour after login in.

**Comment by remocrevo** [comment]
Something you can do today to improve the situation, if you’re using the Auth module:


·         Edit auth/admin/configuration.ini

·         Under [settings], change “timeout” to something larger (ours is 86400, which is 24 hours)

Remington

**Comment by techsvcslib** [comment]
That’s a great thing to know and I’ll ask for this change to be implemented locally.

Steve

On Aug 5, 2016, at 8:08 AM, remocrevo <notifications@github.com<mailto:notifications@github.com>> wrote:

Something you can do today to improve the situation, if you’re using the Auth module:


· Edit auth/admin/configuration.ini

· Under [settings], change “timeout” to something larger (ours is 86400, which is 24 hours)

Remington

**Comment by xsong9** [comment]
It doesn't seem to be an issue on the demo site.
